### ISSUE TITLE
http reporter always call zipkin server even without sampler

### ISSUE THREAD

**Issue by caozhipan** [openzipkin/zipkin-php#118]
hello
I set Sampler Rate=0.01, but qps of zipkin-server didn't fall

then I use tcpdump to catch the tcp packages and found that
![image](https://user-images.githubusercontent.com/5044014/62107378-0780b180-b2da-11e9-8c22-6d8f90389521.png)

finnaly, I found this code 
https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Reporters/Http.php
```php
 /**
     * @param Span[] $spans
     * @return void
     */
    public function report(array $spans): void
    {
        $payload = json_encode(array_map(function (Span $span) {
            return $span->toArray();
        }, $spans));
        if ($payload === false) {
            $this->logger->error(
                sprintf('failed to encode spans with code %d', \json_last_error())
            );
            return;
        }
        $client = $this->clientFactory->build($this->options);
        try {
            $client($payload);
        } catch (RuntimeException $e) {
            $this->logger->error(sprintf('failed to report spans: %s', $e->getMessage()));
        }
    }
```
this function didn't consider that empty $spans

**Comment by jcchavezs** [comment]
Fix is included in the new release: https://github.com/openzipkin/zipkin-php/releases/tag/1.3.4

**Comment by caozhipan** [comment]
@jcchavezs  
Is there any ambiguity in what I said?
In your fix commit, there is just some changes in 'tests/Unit/Reporters/HttpTest.php'  and 'tests/Unit/Reporters/HttpMockFactory.php'

how about the commit : https://github.com/openzipkin/zipkin-php/issues/118

**Comment by jcchavezs** [comment]
Hi @caozhipan my bad.

Currently we have the 1.x.x releases coming form v1 branch and master for the WIP v2. I opened 2 PRs: https://github.com/openzipkin/zipkin-php/pull/120 against `v1` and https://github.com/openzipkin/zipkin-php/pull/119 against `master` but only the master one included the change. Thanks for noticing so quickly so I am preparing a new release.

**Comment by caozhipan** [comment]
@jcchavezs 
great!!!

**Comment by jcchavezs** [comment]
You can try 1.3.4 now: https://github.com/openzipkin/zipkin-php/releases/tag/1.3.4
