### ISSUE TITLE
How to set span failed if api doesn't success?

### ISSUE THREAD

**Issue by doanthai** [openzipkin/zipkin-php#136]
I don't see any code set status of api on span.
When api call failed how to set span failed?

Thanks.

**Comment by jcchavezs** [comment]
Hi @doanthai thanks for reaching out. Such questions are better asked on twitter.

Currently it depends on what your are looking for. It it is on client side, you need to instrument your client (e.g. [guzzle](https://github.com/jcchavezs/zipkin-instrumentation-guzzle/blob/master/src/ZipkinGuzzle/Middleware.php#L72)) or server (e.g. [symfony](https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/Middleware.php#L213)). Feel free to keep this conversation over gitter: https://gitter.im/openzipkin/zipkin

**Comment by doanthai** [comment]
@jcchavezs I want to work on client. I use CodeIgniter Curl Class to send request. Do codeigniter curl support that like guzzle?

**Comment by jcchavezs** [comment]
Do you mean https://github.com/philsturgeon/codeigniter-curl? There is this PR that I will integrate soon and that would help you: https://github.com/openzipkin/zipkin-php/pull/128.

Other than that, you can always wrap the calls yourself (in a function). If you show some code I can help but in general I recommend this questions to be asked over https://gitter.im/openzipkin/zipkin

**Comment by jcchavezs** [comment]
Closing as no more feedback. Feel free to reopen it if you still need help with this.
