### ISSUE TITLE
Declaration of ZipkinOpenTracing\Tracer::getScopeManager() must be compatible with OpenTracing\Tracer::getScopeManager(): OpenTracing\ScopeManager in /var/www/vendor/jcchavezs/zipkin-opentracing/src/ZipkinOpenTracing/Tracer.php on line 47

### ISSUE THREAD

**Issue by cjzyy** [openzipkin/zipkin-php#138]
i use it，but that show "Declaration of ZipkinOpenTracing\Tracer::getScopeManager() must be compatible with OpenTracing\Tracer::getScopeManager()",how to deal with it？

**Comment by jcchavezs** [comment]
Issue should be opened in https://github.com/jcchavezs/zipkin-php-opentracing. Are you using opentracing master?
