### ISSUE TITLE
Can we make Tracer not final?

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin-php#152]
I'm unable to mock it out in unit tests
```
Mockery\Exception: The class \Zipkin\Tracer is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as in
stantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks.
```

**Comment by jcchavezs** [comment]
I think since Tracer does not implement any interface it makes sense to remove the final. Would you come up with a PR for that?

**Comment by jcchavezs** [comment]
BTW I always use an actual tracer for tests. The main issue with doing that
is that assertions have to be done over reported spans which is
inconvenient but in the other hand if I use tracer methods I prefer to
assert that spans are created with certain name/kind/tags rather than
asserting how many times a method have been called. Is that an option for
you? I am not 100% sure making the tracer non final is a great idea.

**Comment by jcchavezs** [comment]
One example on how to do it can be found here:

https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/tests/Unit/MiddlewareTest.php#L45 but it is as easy as:

```php
function createTestTracer(): array {
    $reporter = new InMemoryReporter();
    $tracing = TracingBuilder::create()
        ->havingSampler(BinarySampler::createAsAlwaysSample())
        ->havingReporter($reporter)
        ->build();

    $flusher = static function() use ($tracing, $reporter) {
        $tracing->getTracer()->flush();
        return array_map(function($span) {return $span->toArray();}, $reporter->flush());
    }
    return [$tracing, $flusher];
}

function TestSomething() {
    list($tracing, $flusher) = createTestTracer();
    // do something

    $spans = $flusher();
    $this->assertCount(1, $spans);
    $this->assertArraySubset([
        'tags' => [
            'http.host' => self::HTTP_HOST,
            'http.method' => self::HTTP_METHOD,
            'http.path' => self::HTTP_PATH,
            self::TAG_KEY => self::TAG_VALUE,
        ]
    ], $spans[0]);
}
```

**Comment by drolando** [comment]
@jcchavezs yep that example worked!
