### ISSUE TITLE
Possible documentation issue

### ISSUE THREAD

**Issue by andrei-dascalu** [openzipkin/zipkin-php#176]
Hello,

The readme sample shows

```php
$reporter = new Http(['endpoint_url' => 'http://myzipkin:9411/api/v2/spans']);
```

However, the constructor is specified as:

```php
    public function __construct(
        ?ClientFactory $requesterFactory = null,
        array $options = [],
        ?LoggerInterface $logger = null
    ) {
        $this->clientFactory = $requesterFactory ?: CurlFactory::create();
        $this->options = \array_merge(self::DEFAULT_OPTIONS, $options);
        $this->logger = $logger ?? new NullLogger();
    }
```

I would assume the readme should say

```php
$reporter = new Http(null, ['endpoint_url' => 'http://myzipkin:9411/api/v2/spans']);
```

**Comment by jcchavezs** [comment]
Thanks for reaching out @andrei-dascalu. Documentation is for `2.0` whereas you are using `1.x`. I suggest you use `^2.0`, we are in beta but releasing the stable version very soon. Your feedback would be also very valuable.

**Comment by andrei-dascalu** [comment]
Hi,

What I have is this:

```json
    "require": {
        "openzipkin/zipkin": "^2.0@dev"
    },
```

I've also looked in master branch and the constructor looks as above. Perhaps the documentation is for `1.x` ?

**Comment by andrei-dascalu** [comment]
@jcchavezs 

After changing minimum-stability from dev to beta, I got the expected result with version "^2.0".

Seems that on dev, the latest detected tag was "v2.x-dev 620598f", which is a pretty old commit.

Thanks
