### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by andrei-dascalu** [openzipkin/zipkin-php#202]
Hi,

I've noticed that there are 2 PR's already on this topic (#200 and #198 ), so I thought it might be ok to also have an issue about the challenges around this. Also being selfish and all I was hit by the incompatibility with PHP 8 as we're going through a migration process with a couple of projects that also use zipkin.

Given that both PHP 7.1 & PHP 7.2 are past their EOL dates, is there a support target/plan with respect to backwards compatibility of various PHP versions?

Thanks

**Comment by jcchavezs** [comment]
Hi @andrei-dascalu thanks for creating this.

This is something desirable and I hope we can get something functional in the next couple of weeks. Current challenges are mainly on making tests pass. Main blocker is this error https://github.com/openzipkin/zipkin-php/pull/198#issuecomment-813097562

Regarding dropping support for 7.1 and 7.2 I think we can happily cut *3.0* including features only compatible with 7.3+. I could even think about 7.4+ and 8.0 only.

**Comment by andrei-dascalu** [comment]
@jcchavezs I have a proposition about that, if it's ok. I'm going to make a merge request (looks ok in my local but there are some other changes there). What I found is that Guzzlehttp/psr7 doesn't provide PSR-17 factories, only psr7. There's some WIP there but so far in similar situations I found nyholm to be more usable in that it provides both.

**Comment by andrei-dascalu** [comment]
Party on! Looking forward to v3.

**Comment by jcchavezs** [comment]
Do you have in mind any features we can benefit from PHP 7.3+? I think
JSON_THROW_ON_ERROR and maybe properties type. Besides that I think a great
set of features could be added when 8.0 is landed (e.g. usage of
annotations for autotracing).

Do we need to support 7.3 or just go with 7.4 for v3.0?

Any thoughts @limingxinleo @FutureMatt?

**Comment by limingxinleo** [comment]
I don't think php8 is popular yet, so it's necessary to support php7.3

**Comment by limingxinleo** [comment]
Hi, @jcchavezs 

How long can you deal with this issue?

It's my pleasure to get your reply.

Thanks.

**Comment by jcchavezs** [comment]
I hope we can close a release by end of this month.

**Comment by nocive** [comment]
bump

**Comment by jcchavezs** [comment]
@limingxinleo Do you think is still needed to support PHP 7.3? I think we can have PHP 7.3 in 2.0 and support only PHP 7.4 in 3.0 then we don't need to carry on supporting 7.3 in 3.0 too long.

**Comment by jcchavezs** [comment]
I am doing a clean up for deprecations and soon will release 3.0.

**Comment by limingxinleo** [comment]
No, I think 7.3 isn't needed.

**Comment by diankemao** [comment]
No, I think 7.3 isn't needed.   Support for PHP 8.x OR 7.4

**Comment by diankemao** [comment]
@jcchavezs Please support for PHP 7.4 AND 8.0 AND 8.1，8.1 Coming Soon

**Comment by diankemao** [comment]
@jcchavezs @limingxinleo Please support for PHP 7.4 AND 8.0 AND 8.1，8.1 Coming Soon

**Comment by jcchavezs** [comment]
@diankemao https://github.com/openzipkin/zipkin-php/pull/217

**Comment by jcchavezs** [comment]
I am going to release 3.0 today unless someone says otherwise.

**Comment by nocive** [comment]
Did someone say otherwise? It's been 2 days :angel:

**Comment by diankemao** [comment]
no, please release 3.0

**Comment by jcchavezs** [comment]
Release 3.0 is out, thanks to everyone here for their contributions! https://github.com/openzipkin/zipkin-php/releases/tag/3.0.0
