### ISSUE TITLE
Not using OT interfaces

### ISSUE THREAD

**Issue by Hoten** [openzipkin/zipkin-php#90]
I noticed that this package doesn't use the OT interfaces (opentracing/opentracing-php). I'm still trying to understand this whole OT ecosystem - is this temporary (the interfaces weren't ready?), or the result of a purposeful design decision?

**Comment by adriancole** [comment]
OT is library api, it is not an implementation, eg it does not define B3 or
a data format which is needed to send trace data. You can't instrument
fully with OT libraries. Usually things like service identification and
sampling etc are left as tag heuristics which leads to poor experience vs
apis and models.

Not everyone believe binding to OT interfaces are a good idea. In fact,
most tracers do not do this. Usually APM systems support a bridge model,
when supporting OT. OT is also not the only abstraction choice, there is
also opencensus for example, which is also not OT. Then there are popular
libraries that use neither, like Amazon X-Ray. Of course there are a couple
systems that are "all-in" on opentracing, or seem that way in so far as
their formal clients use OT. So far as I can tell that is jaeger and
recently expedia haystack. However, even jaeger, the cofounders of OT are
involved in census: an api competitor with OT! Generally speaking tracing
systems would be or will be more open than just supporting opentracing, as
it doesn't represent the largest share of value or site deployments.

Anyway, shorter answer is the programming api and model here are based on
what works best for Zipkin and things we export to.

**Comment by Hoten** [comment]
Thank you for the thorough response. I'm understanding it more clearly now. I admittedly just learned about distributed tracing, via OT, so that has been shaping my viewpoint so far.

**Comment by adriancole** [comment]
no worries. feel free to hop on https://gitter.im/openzipkin/zipkin to chat
more

**Comment by jcchavezs** [comment]
As @adriancole bridge model is the most common case. There is this brigde https://github.com/jcchavezs/zipkin-php-opentracing for `zipkin-php`.
