### ISSUE TITLE
Supporting Timeout as an Option for Reporter

### ISSUE THREAD

**Issue by Aideen-Nasirishargh-CK** [openzipkin/zipkin-php#94]
Since PHP is not a multi-threaded programming language, it's good to support passing a timeout value to the reporter.  Clearly, the timeout for this Reported might need to be different from the general timeout value of PHP/Apache for other calls, so passing it as an `option` can be a good idea.

**Comment by Aideen-Nasirishargh-CK** [comment]
https://github.com/openzipkin/zipkin-php/pull/93 is a PR for this.

**Comment by jcchavezs** [comment]
Version [1.3.2](https://github.com/openzipkin/zipkin-php/tree/1.3.2) is out :tada:
