### ISSUE TITLE
Reporter silent error handling

### ISSUE THREAD

**Issue by telemmaite** [openzipkin/zipkin-php#95]
Currently it is hard to debug/understand when our `spans` are not accepted by the `zipkin Server`.

For instance my **Zipkin client** was sending a `null` value in a tag by doing 
`$span->tag('curl.total_time', $info['total_time']); //total_time was null`

`Zipkin Server` response was `400` but that was hidden from me because of the try/catch block here 
https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Reporters/Http.php#L63

I suggest adding **Debug** mode or **Verbosity config** to the client so that we know when things start failing for some reason.

**Comment by jcchavezs** [comment]
Thanks @telemmaite!

I see two issues here, the first one is whether we cast to string the value
for a tag when [receiving it](
https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/RealSpan.php#L130)
or when [reporting it](
https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Recording/Span.php
).

Any input @adriancole?

José Carlos Chávez


Den ons. 10. okt. 2018 kl. 14:55 skrev telemmaite <notifications@github.com

**Comment by adriancole** [comment]
in java side we have a metrics handler which can be implemented via logging
of one so desired as well

**Comment by jcchavezs** [comment]
Yeah, we could implement a metric reporter implementing the `Metrics.php` interface but sending data to stdout. What do you think? @telemmaite

**Comment by telemmaite** [comment]
I checked a little the Java side project, to me it looks like the `metrics handler` is a type of **Collector** which has 4 components  
[Collector.java](https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/core/src/main/java/zipkin2/collector/Collector.java#L82)
```  
final Logger logger;
final CollectorMetrics metrics;
final CollectorSampler sampler;
final StorageComponent storage;
```
In PHP side we have interface [Zipkin/Reporters/Metrics.php](https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Reporters/Metrics.php)
Which looks like it maps to Java side [CollectorMetrics interface](https://github.com/openzipkin/zipkin/blob/a40ebcb47986ed1efb85a0543a17611d78404eb2/zipkin-collector/core/src/main/java/zipkin2/collector/CollectorMetrics.java)

Maybe a new **Collector** class which brings together the metrics + logger functionality is the correct option?
I see the **Metrics** interface is all about incr/decr so it will be strange to re purpose to include a logger.

Hopefully I am not confused as I am very new to all those projects.

**Comment by adriancole** [comment]
sorry the project is zipkin-reporter-java on github.

one reason to use a handler even if not named metrics is to not have logger
overhead by default

**Comment by jcchavezs** [comment]
@telemmaite this PR adds a logger into the reporter API: https://github.com/openzipkin/zipkin-php/pull/107. This is something that people was requesting and ti seems like none was using the metrics API.
